name: FooPolymer
description: A sample Polymer application
dependencies:
  core_elements: any
  paper_elements: any
  polymer: '>=0.12.0 <0.13.0'
  redstone: any
  shelf_static: any
transformers:
- polymer:
    entry_points: web/foopolymer.html
