FROM ubuntu:14.04

RUN apt-get update
RUN apt-get install -y nginx
RUN rm /etc/nginx/sites-enabled/default
RUN echo "daemon off;" >> /etc/nginx/nginx.conf

#
# install etcdctl
#
RUN wget -q https://github.com/coreos/etcd/releases/download/v0.3.0/etcd-v0.3.0-linux-amd64.tar.gz -O /tmp/etcd.tar.gz &&\
    cd /tmp && tar xfz etcd.tar.gz && \
    mv etcd-v0.3.0-linux-amd64/etcdctl /usr/local/bin && \
    rm -rf etcd-v0.3.0-linux-amd64 etcd.tar.gz

EXPOSE 80 443
CMD ["nginx"]
